{
 "title": "dash-go-products-api",
 "description": "Saúde da go-products-api",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "API RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL REQUESTS/SEC",
   "type": "stat",
   "description": "Total requests per second",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(echo_http_request_duration_count{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERROR 500",
   "type": "stat",
   "description": "Number of 500 errors in last minute",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\", code=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WIP: LATENCY AVERAGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum(rate(echo_http_request_duration_bucket{application=\"go-products-api\", path!=\"/metrics\", path!~\"^/swagger.*\"}[1m])) by (le)))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, (sum(rate(echo_http_request_duration_bucket{application=\"go-products-api\", path!=\"/metrics\", path!~\"^/swagger.*\"}[1m])) by (le)))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, (sum(rate(echo_http_request_duration_bucket{application=\"go-products-api\", path!=\"/metrics\", path!~\"^/swagger.*\"}[1m])) by (le)))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, (sum(rate(echo_http_request_duration_bucket{application=\"go-products-api\", path!=\"/metrics\", path!~\"^/swagger.*\"}[1m])) by (le)))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, (sum(rate(echo_http_request_duration_bucket{application=\"go-products-api\", path!=\"/metrics\", path!~\"^/swagger.*\"}[1m])) by (le)))",
     "legendFormat": "25%"
    }
   ]
  },
  {
   "title": "ERROR RATE",
   "type": "timeseries",
   "description": "Error Rate in last 5 minutes",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\", code=\"500\"}[5m])) / sum(rate(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\"}[5m]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(rate(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\", code=\"400\"}[5m])) / sum(rate(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\"}[5m]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(rate(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\", code=\"404\"}[5m])) / sum(rate(echo_http_requests_total{application=\"$application\", path!=\"/metrics\", path!~\"^/swagger.*\"}[5m]))",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "RESPONSE TIME",
   "type": "timeseries",
   "description": "Means latency in last minute",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(echo_http_request_duration_sum{application=\"go-products-api\", path!=\"/metrics\", path!~\"^/swagger.*\"}[5m])",
     "legendFormat": "{{path}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "REQUEST COUNT",
   "type": "timeseries",
   "description": "Requests number per endoint in last minute",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(echo_http_request_duration_sum{application=\"$application\", path=\"/products/:product_id\"}[1m])) * 1000",
     "legendFormat": "/products/:product_id"
    },
    {
     "expr": "sum(increase(echo_http_request_duration_sum{application=\"$application\", path=\"/products\"}[1m])) * 1000",
     "legendFormat": "/products"
    }
   ]
  },
  {
   "title": "AVERAGE REQUEST DURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(echo_http_request_duration_sum{application=\"$application\", code=\"200\", path=\"/products/:product_id\"}[1m]) / rate(echo_http_request_duration_count{application=\"$application\", code=\"200\", path=\"/products/:product_id\"}[1m])",
     "legendFormat": "{{path}} {{method}} {{code}}"
    },
    {
     "expr": "rate(echo_http_request_duration_sum{application=\"$application\", code=\"200\", path=\"/products\"}[1m]) / rate(echo_http_request_duration_count{application=\"$application\", code=\"200\", path=\"/products\"}[1m])",
     "legendFormat": "{{path}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "MAX REQUEST DURATION",
   "type": "timeseries",
   "description": "Maximun durantion of request",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "echo_http_requests_total{application=\"$application\", code=\"200\", path !=\"/metrics\", path!~\"^/swagger.*\"}",
     "legendFormat": "{{path}} {{method}} {{code}}"
    }
   ]
  },
  { "title": "API BASICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "START TIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARN & ERROR LOG",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(log_events_total{application=\"$application\", level=\"info\"}[5m]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(increase(log_events_total{application=\"$application\", level=\"warning\"}[5m]))",
     "legendFormat": "warning"
    },
    {
     "expr": "sum(increase(log_events_total{application=\"$application\", level=\"error\"}[5m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "DB CONNECTION STATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gorm_dbstats_in_use{application=\"$application\"}",
     "legendFormat": "In Use"
    },
    {
     "expr": "gorm_dbstats_idle{application=\"$application\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "gorm_dbstats_wait_count{application=\"$application\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  { "title": "API USE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "MEMORY ALLOC USE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_alloc_bytes{application=\"$application\"})*100 / sum(memory_total_alloc_bytes{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\"}",
     "legendFormat": "System CPU usage"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\"}",
     "legendFormat": "Process CPU usage"
    }
   ]
  },
  {
   "title": "MEMORY AVERAGE USE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(memory_used_bytes{application=\"$application\"}) / sum(memory_limit_bytes{application=\"$application\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOAD AVERAGE",
   "type": "timeseries",
   "description": "CPU usage mean",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 45 },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\"}",
     "legendFormat": "Load average [1m]"
    },
    {
     "expr": "system_cpu_cores{application=\"$application\"}",
     "legendFormat": "CPU core size"
    }
   ]
  }
 ]
}